CREATE DATABASE GuiaResueltaEjercicio1
GO
USE GuiaResueltaEjercicio1
GO

CREATE TABLE Escuela
(
	Codigo INT IDENTITY(1, 1) PRIMARY KEY,
	Nombre VARCHAR (50), 
	Direccion VARCHAR (255)
);

CREATE TABLE Alimento
(
	Id INT IDENTITY(1, 1) PRIMARY KEY,
	Descripcion	VARCHAR (50),
	Marca VARCHAR (50)
);

CREATE TABLE Alumno
(
	DNI	INT NOT NULL PRIMARY KEY, 
	Apellido VARCHAR (50), 
	Nombre VARCHAR (50), 
	CodigoEscuela INT,
);

ALTER TABLE Alumno ADD CONSTRAINT FK_Alumno_CodigoEscuela FOREIGN KEY (CodigoEscuela) REFERENCES Escuela (Codigo) ON DELETE CASCADE ON UPDATE CASCADE;

CREATE TABLE HermanoDe
(
	DNIAlumno INT NOT NULL, 
	DNIHermano INT NOT NULL, 
	CONSTRAINT PK_HermanoDe PRIMARY KEY (DNIAlumno, DNIHermano)
);

ALTER TABLE HermanoDe ADD CONSTRAINT FK_HermanoDe_DNIAlumno FOREIGN KEY (DNIAlumno) REFERENCES Alumno (DNI) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE HermanoDe ADD CONSTRAINT FK_HermanoDe_DNIHermano FOREIGN KEY (DNIHermano) REFERENCES Alumno (DNI) ON DELETE NO ACTION ON UPDATE NO ACTION;

CREATE TABLE AlmuerzaEn
(
	DNIAlumno INT NOT NULL, 
	IdAlimento INT NOT NULL, 
	CodigoEscuela INT, 
	CONSTRAINT PK_AlmuerzaEn PRIMARY KEY (DNIAlumno, IdAlimento)
);

ALTER TABLE AlmuerzaEn ADD CONSTRAINT FK_AlmuerzaEn_DNIAlumno FOREIGN KEY (DNIAlumno) REFERENCES Alumno (DNI) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE AlmuerzaEn ADD CONSTRAINT FK_AlmuerzaEn_IdAlimento FOREIGN KEY (IdAlimento) REFERENCES Alimento (Id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE AlmuerzaEn ADD CONSTRAINT FK_AlmuerzaEn_CodigoEscuela FOREIGN KEY (CodigoEscuela) REFERENCES Escuela (Codigo) ON DELETE NO ACTION ON UPDATE NO ACTION;